<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-01T16:34:04 IST" name="Default suite" finished-at="2022-05-01T16:34:13 IST" duration-ms="9632">
    <groups>
    </groups>
    <test started-at="2022-05-01T16:34:04 IST" name="Default test" finished-at="2022-05-01T16:34:13 IST" duration-ms="9632">
      <class name="AssertTypes.Softassert">
        <test-method is-config="true" signature="chromeRun()[pri:0, instance:AssertTypes.Softassert@6da21078]" started-at="2022-05-01T16:34:04 IST" name="chromeRun" finished-at="2022-05-01T16:34:09 IST" duration-ms="4990" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- chromeRun -->
        <test-method signature="test1()[pri:1, instance:AssertTypes.Softassert@6da21078]" started-at="2022-05-01T16:34:09 IST" name="test1" finished-at="2022-05-01T16:34:09 IST" duration-ms="29" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="close()[pri:0, instance:AssertTypes.Softassert@6da21078]" started-at="2022-05-01T16:34:09 IST" name="close" finished-at="2022-05-01T16:34:09 IST" duration-ms="430" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="chromeRun()[pri:0, instance:AssertTypes.Softassert@6da21078]" started-at="2022-05-01T16:34:09 IST" name="chromeRun" finished-at="2022-05-01T16:34:13 IST" duration-ms="3445" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- chromeRun -->
        <test-method signature="test2()[pri:2, instance:AssertTypes.Softassert@6da21078]" started-at="2022-05-01T16:34:13 IST" name="test2" finished-at="2022-05-01T16:34:13 IST" duration-ms="11" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
title not matched expected [Google123] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
title not matched expected [Google123] but found [Google]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at AssertTypes.Softassert.test2(Softassert.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="close()[pri:0, instance:AssertTypes.Softassert@6da21078]" started-at="2022-05-01T16:34:13 IST" name="close" finished-at="2022-05-01T16:34:13 IST" duration-ms="677" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- AssertTypes.Softassert -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
